dir = File.dirname(__FILE__) + '/cb-music-theory'
require dir + '/note'
require dir + '/note_interval'
require dir + '/root_note_with_intervals'
require dir + '/chord'
require dir + '/scale'
require dir + '/experimental_scales'
require dir + '/instrument/guitar/guitar_string'
require dir + '/instrument/guitar/guitar'
